stef_generate_fixtures:
    resource: "@StefGenerateFixturesBundle/Controller/"
    type:     annotation
    prefix:   /

stef_bv:
    resource: "@StefBVBundle/Resources/config/routing.yml"
    prefix:   /
