stef_photo_homepage:
    path:     /fotoalbum
    defaults: { _controller: StefPhotoBundle:Photo:showAllAlbums }

stef_photo_season:
    path:     /fotoalbum/{year_1}-{year_2}
    defaults: { _controller: StefPhotoBundle:Photo:showAllAlbums }

stef_photo_showalbum:
    path:     /fotoalbum/{year_1}-{year_2}/{album}
    defaults: { _controller: StefPhotoBundle:Photo:showAlbum }