

#example pages
stef_bvbundle_homepage:
    pattern:  /
    defaults: { _controller: StefBVBundle:Page:index }
    requirements:
        _method:  GET

stef_bvbundle_about:
    pattern:  /about
    defaults: { _controller: StefBVBundle:Page:about }
    requirements:
        _method:  GET

stef_bvbundle_contact:
    pattern:  /contact
    defaults: { _controller: StefBVBundle:Page:contact }
    requirements:
        _method:  GET|POST

stef_bvbundle_blog_show:
    pattern:  /{id}
    defaults: { _controller: StefBVBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+



#Webpages - News
stef_bvbundle_news_archive_current_year_show:
    pattern:  /nieuws/archief
    defaults: { _controller: StefBVBundle:News:showArchive }
    requirements:
        _method:  GET

stef_bvbundle_news_archive_show:
    pattern:  /nieuws/archief/{year}
    defaults: { _controller: StefBVBundle:News:showArchive }
    requirements:
        _method:  GET

stef_bvbundle_news_show:
    pattern:  /nieuws/{slug}
    defaults: { _controller: StefBVBundle:News:show }
    requirements:
        _method:  GET

#Webpages - Pages (last resort, if anything else is not true)
stef_bvbundle_view_page:
    pattern:  /{slug}
    defaults: { _controller: StefBVBundle:Page:viewPage }
    requirements:
        _method:  GET
        slug: .+