stef_bvbundle_sitemaps:
    pattern:  /sitemaps/{mappingKey}.xml
    defaults: { _controller: StefBVBundle:Sitemap:generate }
    requirements:
        _method:  GET
        _format:  xml

stef_bvbundle_news_archive_current_year_show:
    pattern:  /nieuws/archief
    defaults: { _controller: StefBVBundle:News:showArchive }
    requirements:
        _method:  GET

stef_bvbundle_news_archive_show:
    pattern:  /nieuws/archief/{year}
    defaults: { _controller: StefBVBundle:News:showArchive }
    requirements:
        _method:  GET

stef_bvbundle_dictionary_item:
    pattern:  /begrippenlijst/{slug}
    defaults: { _controller: StefBVBundle:Dictionary:show }
    requirements:
        _method:  GET

stef_bvbundle_dictionary_index:
    pattern:  /begrippenlijst
    defaults: { _controller: StefBVBundle:Dictionary:index }
    requirements:
        _method:  GET

stef_bvbundle_dictionary_alphabetic_index:
    pattern:  /begrippenlijst-{letter}
    defaults: { _controller: StefBVBundle:Dictionary:index }
    requirements:
        _method:  GET
        letter: .+

stef_bvbundle_news_archive_index:
    pattern:  /nieuws
    defaults: { _controller: StefBVBundle:News:showMainNewsPage }
    requirements:
        _method:  GET

stef_bvbundle_news_show:
    pattern:  /nieuws/{slug}
    defaults: { _controller: StefBVBundle:News:show }
    requirements:
        _method:  GET

stef_bvbundle_view_page:
    pattern:  /{slug}
    defaults: { _controller: StefBVBundle:Page:viewPage }
    requirements:
        _method:  GET
        slug: .+

stef_bvbundle_home_page:
    pattern:  /
    defaults: { _controller: StefBVBundle:Page:index }
    requirements:
        _method:  GET
        slug: .+