stef_bvadminbundle_add_news:
    pattern:  /cms/news/add
    defaults: { _controller: StefBVAdminBundle:AdminNews:create }
    requirements:
        _method:  GET|POST

stef_bvadminbundle_edit_news:
    pattern:  /cms/news/{id}
    defaults: { _controller: StefBVAdminBundle:AdminNews:update }
    requirements:
        _method:  GET|POST

stef_bvadminbundle_index_news:
    pattern:  /cms/news
    defaults: { _controller: StefBVAdminBundle:AdminNews:index }
    requirements:
        _method:  GET