stef_bvbundle_admin_add_news:
    pattern:  /cms/news/add
    defaults: { _controller: StefBVBundle:AdminNews:create }
    requirements:
        _method:  GET|POST

stef_bvbundle_admin_edit_news:
    pattern:  /cms/news/{id}
    defaults: { _controller: StefBVBundle:AdminNews:update }
    requirements:
        _method:  GET|POST

stef_bvbundle_admin_index_news:
    pattern:  /cms/news
    defaults: { _controller: StefBVBundle:AdminNews:index }
    requirements:
        _method:  GET