stef_bvadminbundle_add_page:
    pattern:  /cms/pages/add
    defaults: { _controller: StefBVAdminBundle:AdminPage:create }
    requirements:
        _method:  GET|POST

stef_bvadminbundle_edit_page:
    pattern:  /cms/pages/{id}
    defaults: { _controller: StefBVAdminBundle:AdminPage:update }
    requirements:
        _method:  GET|POST

stef_bvadminbundle_index_page:
    pattern:  /cms/pages
    defaults: { _controller: StefBVAdminBundle:AdminPage:index }
    requirements:
        _method:  GET